import { Hono } from 'hono'
import { cors } from 'hono/cors'
import Anthropic from '@anthropic-ai/sdk'
import { readFileSync, writeFileSync, unlinkSync, existsSync, mkdirSync, readdirSync, statSync } from 'fs'
import { join, resolve, sep } from 'path'
import { homedir } from 'os'

const app = new Hono()
app.use('*', cors())

const OUTPUT_DIR           = join(import.meta.dir, 'output')
const FRAMEWORKS_DIR        = join(import.meta.dir, 'frameworks')
const CAROUSELS_DIR         = join(import.meta.dir, 'carousels')
const THEMES_DIR            = join(import.meta.dir, 'themes')
// Where finished carousels land. Defaults to a folder inside the app so a fresh
// clone works with no configuration; point it somewhere else (e.g. a content
// repo) with CAROUSEL_EXPORT_DIR or `exportDir` in settings.json.
function exportDir(): string {
  const configured = process.env.CAROUSEL_EXPORT_DIR || readSettings().exportDir
  if (!configured) return join(import.meta.dir, 'exports')
  return expandPath(configured)
}

/** Content type for a served media file. One source of truth: every route
 *  that streams from disk had its own guess, and each defaulted to an image
 *  type, so an mp4 came back labelled as a picture and would not play. */
function mediaType(name: string): string {
  const ext = name.slice(name.lastIndexOf('.')).toLowerCase()
  return ({
    '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
    '.webp': 'image/webp', '.gif': 'image/gif',
    '.mp4': 'video/mp4', '.mov': 'video/quicktime', '.webm': 'video/webm',
    '.pdf': 'application/pdf',
  } as Record<string, string>)[ext] ?? 'application/octet-stream'
}

/** `~` in a configured path means the user's home directory. */
function expandPath(p: string): string {
  return p.startsWith('~')
    ? join(homedir(), p.slice(1).replace(/^[/\\]/, ''))
    : resolve(p)
}
// Local image library. Anything dropped here — including batches generated by
// the Claude Code kie-* skills — shows up in the app's Image Library.
// Override with CAROUSEL_IMAGES_DIR or `imagesDir` in settings.json.
/** Audio beds for generated video. Empty by default; see audio/README.md. */
function audioDir(): string {
  const configured = process.env.CAROUSEL_AUDIO_DIR || readSettings().audioDir
  if (!configured) return join(import.meta.dir, 'audio')
  return expandPath(configured)
}
function imagesDir(): string {
  const configured = process.env.CAROUSEL_IMAGES_DIR || readSettings().imagesDir
  if (!configured) return join(import.meta.dir, 'images')
  return expandPath(configured)
}
const SETTINGS_FILE         = join(import.meta.dir, 'settings.json')

// Cached: readSettings() reads like a cheap accessor, which is how it ended up
// inside the per-slide export loop. It is a readFileSync + JSON.parse.
let settingsCache: Record<string, any> | null = null
function readSettings(): Record<string, any> {
  if (settingsCache) return settingsCache
  try { settingsCache = JSON.parse(readFileSync(SETTINGS_FILE, 'utf8')) } catch { settingsCache = {} }
  return settingsCache!
}
function writeSettings(data: Record<string, any>) {
  const merged = { ...readSettings(), ...data }
  settingsCache = null
  writeFileSync(SETTINGS_FILE, JSON.stringify(merged, null, 2))
}

/** The audio bed to lay under a video: what the caller asked for, else the
 *  configured default, else nothing. Never guesses at a file on disk. */
function resolveAudio(requested?: string): string | undefined {
  const explicit = requested ? resolveMediaPath(requested) : null
  if (explicit) return explicit
  const configured = readSettings().audioPath
  if (!configured) return undefined
  const abs = expandPath(configured.startsWith('/') || configured.startsWith('~')
    ? configured : join(import.meta.dir, configured))
  return existsSync(abs) ? abs : undefined
}

/** Export folder name for a carousel title. Mirrored by slugify() in App.tsx. */
function slugFromTitle(title: string): string {
  return (title || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'carousel'
}

/** Creator handle shown on CTA slides and in the platform preview mockups. */
function creatorHandle(): string {
  const h = (readSettings().handle || '@yourhandle').trim()
  return h.startsWith('@') ? h : `@${h}`
}

mkdirSync(OUTPUT_DIR,    { recursive: true })
mkdirSync(CAROUSELS_DIR, { recursive: true })
try { mkdirSync(imagesDir(), { recursive: true }) } catch { /* non-fatal */ }

// Resolve a client-side media URL to an absolute path on disk.
// Accepts '/files/<name>' (generated output) and '/carousel-output/<slug>/<name>'
// (exported carousels). Returns null for anything else, or for any path that
// escapes its base directory.
function resolveMediaPath(url: string | undefined): string | null {
  if (!url) return null
  let base: string
  let rel: string
  if (url.startsWith('/files/')) {
    base = OUTPUT_DIR
    rel  = url.slice('/files/'.length)
  } else if (url.startsWith('/carousel-output/')) {
    base = exportDir()
    rel  = url.slice('/carousel-output/'.length)
  } else if (url.startsWith('/local-images/')) {
    base = imagesDir()
    rel  = url.slice('/local-images/'.length)
  } else if (url.startsWith('/local-audio/')) {
    base = audioDir()
    rel  = url.slice('/local-audio/'.length)
  } else {
    return null
  }
  const resolved = resolve(base, decodeURIComponent(rel))
  if (resolved !== base && !resolved.startsWith(base + sep)) return null
  return existsSync(resolved) ? resolved : null
}

// Load API keys. A .env in the project root is the normal case; ~/.claude/.env
// is also read so the app works inside a Claude Code setup without duplicating
// keys. Real environment variables always win over both.
function loadEnv() {
  for (const envPath of [join(import.meta.dir, '.env'), join(homedir(), '.claude', '.env')]) {
    try {
      for (const line of readFileSync(envPath, 'utf8').split('\n')) {
        const t = line.trim()
        if (!t || t.startsWith('#')) continue
        const eq = t.indexOf('=')
        if (eq === -1) continue
        const key = t.slice(0, eq).trim()
        const val = t.slice(eq + 1).trim().replace(/^["']|["']$/g, '')
        if (!process.env[key]) process.env[key] = val
      }
    } catch { /* file absent — fine */ }
  }
}
loadEnv()

// ── App Settings (likeness path, etc.) ───────────────────────────────────────

app.get('/api/settings', (c) => c.json(readSettings()))

app.post('/api/settings', async (c) => {
  const body = await c.req.json()
  writeSettings(body)
  return c.json({ ok: true, settings: readSettings() })
})

// ── Themes ────────────────────────────────────────────────────────────────────

// A theme is one JSON file in themes/. Drop a file in, reload the app, and it
// shows up — no rebuild, no code change. See themes/README.md for the fields.
app.get('/api/themes', (c) => {
  try {
    const themes = readdirSync(THEMES_DIR)
      .filter((f) => f.endsWith('.json'))
      .map((f) => {
        try {
          const t = JSON.parse(readFileSync(join(THEMES_DIR, f), 'utf8'))
          if (!t.bgColor || !t.textColor || !t.accentColor) return null
          return { ...t, id: t.id || f.replace(/\.json$/, ''), builtin: true }
        } catch { return null }   // one malformed file must not hide the rest
      })
      .filter(Boolean)
      // Explicit `order` keeps the swatch row stable; readdir order is not.
      .sort((a: any, b: any) => (a.order ?? 999) - (b.order ?? 999) || a.name.localeCompare(b.name))
    return c.json(themes)
  } catch {
    return c.json([])
  }
})

// ── Carousel Save / Load ──────────────────────────────────────────────────────

// List all saved carousels (newest first)
app.get('/api/carousels', (c) => {
  const files = readdirSync(CAROUSELS_DIR).filter((f) => f.endsWith('.json'))
  const list = files
    .map((f) => {
      try {
        const d = JSON.parse(readFileSync(join(CAROUSELS_DIR, f), 'utf8'))
        // What has actually been exported for this carousel, so the Library can
        // say whether an Instagram, TikTok or video version exists rather than
        // making you open the Exports gallery to find out.
        const slug = slugFromTitle(d.title)
        const slugDir = join(exportDir(), slug)
        let exported: string[] = []
        let hasVideo = false
        if (existsSync(slugDir)) {
          try {
            const files = readdirSync(slugDir, { withFileTypes: true })
            if (files.some((x) => x.isFile() && /^slide_\d+\.(png|mp4)$/i.test(x.name))) exported.push('default')
            for (const sub of files.filter((x) => x.isDirectory())) {
              try {
                if (readdirSync(join(slugDir, sub.name)).some((n) => /^slide_\d+\./i.test(n))) exported.push(sub.name)
              } catch { /* ignore */ }
            }
            hasVideo = files.some((x) => x.isFile() && /\.(mp4|mov|webm)$/i.test(x.name) && !/^slide_\d+\./i.test(x.name))
          } catch { /* ignore */ }
        }
        return {
          id: d.id, title: d.title, platform: d.platform,
          slideCount: d.slides?.length ?? 0, savedAt: d.savedAt,
          slug, exported, hasVideo,
        }
      } catch { return null }
    })
    .filter(Boolean)
    .sort((a: any, b: any) => new Date(b.savedAt).getTime() - new Date(a.savedAt).getTime())
  return c.json(list)
})

// Save / upsert a carousel
app.post('/api/carousels', async (c) => {
  const body = await c.req.json()
  const id   = body.id || `carousel_${Date.now()}`
  const data = { ...body, id, savedAt: new Date().toISOString() }
  writeFileSync(join(CAROUSELS_DIR, `${id}.json`), JSON.stringify(data, null, 2))
  return c.json({ id, savedAt: data.savedAt })
})

// Load a carousel
app.get('/api/carousels/:id', (c) => {
  const path = join(CAROUSELS_DIR, `${c.req.param('id')}.json`)
  if (!existsSync(path)) return c.json({ error: 'Not found' }, 404)
  return c.json(JSON.parse(readFileSync(path, 'utf8')))
})

// Delete a carousel
app.delete('/api/carousels/:id', (c) => {
  const path = join(CAROUSELS_DIR, `${c.req.param('id')}.json`)
  if (existsSync(path)) unlinkSync(path)
  return c.json({ ok: true })
})

// ── Frameworks ────────────────────────────────────────────────────────────────

app.get('/api/frameworks', (c) => {
  try {
    const files = readdirSync(FRAMEWORKS_DIR).filter((f) => f.endsWith('.json'))
    const frameworks = files.map((f) => {
      const raw = readFileSync(join(FRAMEWORKS_DIR, f), 'utf8')
      const fw = JSON.parse(raw)
      // Don't send the full systemPrompt to the client - keep it server-side
      const { systemPrompt, ...publicFramework } = fw
      return publicFramework
    })
    return c.json(frameworks)
  } catch (err) {
    return c.json({ error: String(err) }, 500)
  }
})

// ── AI Generation ─────────────────────────────────────────────────────────────

app.post('/api/ai-generate', async (c) => {
  const { topic, frameworkId, platform = 'instagram', handle = '' } = await c.req.json()
  if (!topic?.trim()) return c.json({ error: 'topic is required' }, 400)
  if (!frameworkId)    return c.json({ error: 'frameworkId is required' }, 400)
  try {
    const result = await generateSlides(topic, frameworkId, platform, handle)
    return c.json(result)
  } catch (err) {
    return c.json({ error: String(err) }, 500)
  }
})

// Bulk generate + auto-save multiple carousels at once
// POST /api/bulk-generate
// body: { items: [{topic, frameworkId, platform?, handle?}] }
// returns: { results: [{id, title, savedAt, error?}] }
app.post('/api/bulk-generate', async (c) => {
  const { items } = await c.req.json()
  if (!Array.isArray(items) || items.length === 0) return c.json({ error: 'items array is required' }, 400)

  const results: { id: string; title: string; savedAt: string; error?: string }[] = []

  for (const item of items) {
    const { topic, frameworkId, platform = 'instagram', handle = '' } = item
    if (!topic?.trim() || !frameworkId) {
      results.push({ id: '', title: topic ?? '', savedAt: '', error: 'Missing topic or frameworkId' })
      continue
    }
    try {
      const { slides, title } = await generateSlides(topic, frameworkId, platform, handle)
      const id      = `carousel_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`
      const savedAt = new Date().toISOString()
      const data    = { id, title, platform, slides, savedAt }
      writeFileSync(join(CAROUSELS_DIR, `${id}.json`), JSON.stringify(data, null, 2))
      results.push({ id, title, savedAt })
    } catch (err) {
      results.push({ id: '', title: topic, savedAt: '', error: String(err) })
    }
  }

  return c.json({ results })
})

function parseSlidesReply(text: string): { slides: any[]; title: string } {
  // Strip markdown code fences if present
  const cleaned = text.replace(/^```(?:json)?\n?/m, '').replace(/\n?```$/m, '').trim()
  const parsed = JSON.parse(cleaned)
  return {
    slides: parsed.slides ?? [],
    title:  parsed.title  ?? '',
  }
}

/**
 * Scrub a string destined for the monospace terminal window.
 *
 * Models reliably try to decorate these lines with emoji, and the emoji come
 * back mangled — a real reply contained "bash \x1f4BB workspace", a broken
 * U+1F4BB, plus runs of literal tabs. Anything outside printable ASCII renders
 * as tofu in a mono face, so it is stripped here rather than at render time:
 * the stored carousel should be clean.
 */
function cleanMono(s: unknown): string {
  if (typeof s !== 'string') return ''
  return s
    .replace(/[✓✔]/g, '✓')      // normalise both check marks
    .replace(/[\t\r\n]+/g, ' ')                // tabs/newlines break the layout
    // eslint-disable-next-line no-control-regex
    .replace(/[\x00-\x1F\x7F]/g, '')      // control characters
    .replace(/[^\x20-\x7E✓→—]/g, '') // ASCII plus check, arrow, em dash
    .replace(/ {2,}(?=\S)/g, (m) => (m.length > 4 ? '  ' : m)) // collapse runaway padding
    .trimEnd()
}

// JSON Schema the model's response is constrained to, so the reply is always
// valid JSON in the right shape — no markdown fences to strip, no reshaping.
function slidesSchema(slideCount: number, variant?: string) {
  const terminal = variant === 'terminal'
  const props: Record<string, any> = {
    slideNumber:  { type: 'integer' },
    headline:     { type: 'string', description: terminal ? '1-3 words, lowercase, like a CLI subcommand' : '3-6 words, punchy and bold' },
    emphasisLine: { type: 'string', description: '5-12 words, the key insight or hook' },
    bodyText:     { type: 'string', description: '1-3 sentences, practical and specific' },
  }
  if (terminal) {
    props.terminalTitle = { type: 'string', description: 'Window title, e.g. "claude - skill install". PLAIN ASCII ONLY, no emoji. Empty string on the cover and CTA slides.' }
    props.terminalLines = {
      type: 'array',
      items: { type: 'string' },
      description: 'Up to 5 lines of a realistic terminal session. "$ " prefixes the command, "  ✓ " prefixes results. Max 52 characters per line. PLAIN ASCII ONLY — no emoji, no tabs, no box-drawing characters; they render as empty boxes in a monospace font. Empty array on the cover and CTA slides.',
    }
  }
  return {
    type: 'object',
    properties: {
      title: { type: 'string', description: '3-5 word carousel title' },
      slides: {
        type: 'array',
        description: `Exactly ${slideCount} slides, one per slideNumber in order`,
        items: {
          type: 'object',
          properties: props,
          required: Object.keys(props),
          additionalProperties: false,
        },
      },
    },
    required: ['title', 'slides'],
    additionalProperties: false,
  }
}

// Shared AI generation logic used by both /api/ai-generate and /api/bulk-generate
async function generateSlides(topic: string, frameworkId: string, platform = 'instagram', handle = ''): Promise<{ slides: any[]; title: string }> {
  loadEnv()
  const fwPath = join(FRAMEWORKS_DIR, `${frameworkId}.json`)
  if (!existsSync(fwPath)) throw new Error(`Framework "${frameworkId}" not found`)
  const framework = JSON.parse(readFileSync(fwPath, 'utf8'))

  const anthropicKey = process.env.ANTHROPIC_API_KEY
  const openaiKey    = process.env.OPENAI_API_KEY
  if (!anthropicKey && !openaiKey) throw new Error('No AI API key found')

  const handleLine = handle ? `Creator handle: ${handle} — use it on the CTA slide.` : ''
  // Each slide's purpose comes from the framework and tells the model what job
  // that slide does in the arc. The output shape is enforced by the schema, so
  // the prompt only has to cover intent and voice.
  const slidePurposes = framework.slides
    .map((s: any) => `${s.slideNumber}. (${s.type}) ${s.purpose}`)
    .join('\n')

  const userPrompt = `Topic: "${topic}"
Platform: ${platform}
Framework: ${framework.name} — ${framework.description}
${handleLine}

Write all ${framework.slideCount} slides. Each one below lists its slideNumber, type, and the job it does:

${slidePurposes}

Per slide:
- headline: 3-6 words, punchy and bold
- emphasisLine: 5-12 words, the key insight or hook for this slide
- bodyText: 1-3 sentences, practical and specific, no filler

Every slide needs real content written for its specific purpose — no placeholders, no empty strings, no repeating the same point across slides.`

  const systemPrompt = framework.systemPrompt

  let slides: any[]
  let title: string

  if (anthropicKey) {
    const anthropic = new Anthropic({ apiKey: anthropicKey })
    const message = await anthropic.messages.create({
      model: 'claude-opus-5',
      max_tokens: 16000,
      thinking: { type: 'adaptive' },
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
      output_config: { format: { type: 'json_schema', schema: slidesSchema(framework.slideCount, framework.variant) } },
    })
    if (message.stop_reason === 'refusal') {
      throw new Error('Claude declined this topic. Try rewording it.')
    }
    // output_config.format guarantees the first text block is valid JSON
    const text = message.content.find((b) => b.type === 'text')?.text ?? '{}'
    const parsed = parseSlidesReply(text)
    slides = parsed.slides; title = parsed.title
  } else {
    // Fallback path. Uses the same JSON Schema as the Claude path via OpenAI's
    // structured outputs, so both providers return an identically shaped reply.
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${openaiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'gpt-5-mini',
        messages: [{ role: 'system', content: systemPrompt }, { role: 'user', content: userPrompt }],
        response_format: {
          type: 'json_schema',
          json_schema: { name: 'carousel', strict: true, schema: slidesSchema(framework.slideCount, framework.variant) },
        },
      }),
    })
    if (!res.ok) throw new Error(`OpenAI API error ${res.status}: ${await res.text()}`)
    const data = await res.json() as any
    const parsed = parseSlidesReply(data.choices?.[0]?.message?.content ?? '{}')
    slides = parsed.slides; title = parsed.title
  }

  // Merge framework structure with AI content
  const aiByNum: Record<number, any> = {}
  for (const s of (slides ?? [])) aiByNum[s.slideNumber] = s
  const merged = framework.slides.map((fwSlide: any) => {
    const ai = aiByNum[fwSlide.slideNumber] ?? {}
    const { purpose, ...fw } = fwSlide
    const base: any = {
      ...fw,
      headline: ai.headline || '', emphasisLine: ai.emphasisLine || '', bodyText: ai.bodyText || '',
      bgColor: '#F5F0EB', textColor: '#1B1B1B', accentColor: '#E07355',
    }
    if (framework.variant === 'terminal') {
      // Terminal frameworks bring their own palette and layout
      Object.assign(base, {
        variant: 'terminal',
        bgColor: '#12141A', textColor: '#EEECE8', accentColor: '#E07355',
        terminalTitle: cleanMono(ai.terminalTitle) || undefined,
        terminalLines: (ai.terminalLines || []).map(cleanMono).filter(Boolean),
      })
    }
    return base
  })
  for (const s of merged) {
    if (s.type === 'cta' && s.variant !== 'terminal') { s.bgColor = '#1B4332'; s.textColor = '#F5F0EB'; s.accentColor = '#E07355' }
  }

  return { slides: merged, title: title ?? topic }
}

// ── Caption Generation ────────────────────────────────────────────────────────

// POST /api/captions
// body: { title, platform, slides, slug?, save? }
// Writes captions.md next to the exported slides when `save` is set.
app.post('/api/captions', async (c) => {
  const { title, platform = 'instagram', slides = [], slug, save } = await c.req.json()
  if (!Array.isArray(slides) || slides.length === 0) return c.json({ error: 'slides are required' }, 400)

  loadEnv()
  const anthropicKey = process.env.ANTHROPIC_API_KEY
  const openaiKey    = process.env.OPENAI_API_KEY
  if (!anthropicKey && !openaiKey) return c.json({ error: 'No AI API key found' }, 400)

  const outline = slides
    .map((s: any) => `${s.slideNumber}. ${s.headline} — ${s.emphasisLine}. ${s.bodyText}`)
    .join('\n')

  // `brandVoice` in settings.json lets each user describe their own voice; the
  // baseline below is deliberately generic so a fresh install writes decent
  // captions with no configuration.
  const brandVoice = (readSettings().brandVoice || '').trim()
  const system = [
    'You write social captions for a creator posting an educational carousel.',
    'Voice: direct and concrete. Short sentences. Write to one person, not an audience.',
    'Hard rules: never use em dashes. Never invent statistics, results, or testimonials.',
    'Never open with filler like "In today\'s world" or "Let\'s be honest".',
    brandVoice && `Additional voice guidance from the creator: ${brandVoice}`,
  ].filter(Boolean).join(' ')

  const prompt = `Carousel title: "${title}"
Primary platform: ${platform}

Slides:
${outline}

Write captions for this carousel.`

  const schema = {
    type: 'object',
    properties: {
      instagram: { type: 'string', description: 'Instagram caption. Hook on line one, then value, then a soft CTA. No hashtags in this field.' },
      hashtags:  { type: 'array', items: { type: 'string' }, description: 'Exactly 5 Instagram hashtags, each starting with #' },
      linkedin:  { type: 'string', description: 'LinkedIn caption. Slightly longer and more professional. No hashtags at all.' },
    },
    required: ['instagram', 'hashtags', 'linkedin'],
    additionalProperties: false,
  }

  try {
    let parsed: { instagram: string; hashtags: string[]; linkedin: string }

    if (anthropicKey) {
      const anthropic = new Anthropic({ apiKey: anthropicKey })
      const message = await anthropic.messages.create({
        model: 'claude-opus-5',
        max_tokens: 8000,
        thinking: { type: 'adaptive' },
        system,
        messages: [{ role: 'user', content: prompt }],
        output_config: { format: { type: 'json_schema', schema } },
      })
      if (message.stop_reason === 'refusal') throw new Error('Claude declined this topic.')
      parsed = JSON.parse(message.content.find((b) => b.type === 'text')?.text ?? '{}')
    } else {
      const res = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${openaiKey}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'gpt-5-mini',
          messages: [{ role: 'system', content: system }, { role: 'user', content: prompt }],
          response_format: { type: 'json_schema', json_schema: { name: 'captions', strict: true, schema } },
        }),
      })
      if (!res.ok) throw new Error(`OpenAI API error ${res.status}: ${await res.text()}`)
      const data = await res.json() as any
      parsed = JSON.parse(data.choices?.[0]?.message?.content ?? '{}')
    }

    // Strip em dashes defensively — a standing rule for this creator's content
    const stripEmDashes = (s: string) => (s || '').replace(/\s*—\s*/g, ' ')
    const captions = {
      instagram: stripEmDashes(parsed.instagram),
      hashtags:  (parsed.hashtags ?? []).map((h) => (h.startsWith('#') ? h : `#${h}`)),
      linkedin:  stripEmDashes(parsed.linkedin),
    }

    let savedTo: string | null = null
    if (save && slug) {
      const dir = join(exportDir(), slug)
      mkdirSync(dir, { recursive: true })
      const md = `# ${title}\n\n## Instagram\n\n${captions.instagram}\n\n${captions.hashtags.join(' ')}\n\n## LinkedIn\n\n${captions.linkedin}\n`
      const path = join(dir, 'captions.md')
      writeFileSync(path, md)
      savedTo = path
    }

    return c.json({ ...captions, savedTo })
  } catch (err) {
    return c.json({ error: String(err) }, 500)
  }
})

// ── Job queue ─────────────────────────────────────────────────────────────────
//
// Image generation used to hold an SSE connection open for the whole run, owned
// by the Background panel. That blocked a second run, lost results if you
// switched carousels mid-flight, and died on a page refresh.
//
// Jobs live on the server instead. POST returns a jobId immediately, work
// continues in the background, and the client polls. Results carry the
// carouselId they were started for, so they can never land on the wrong one.

type JobResult = { slideNumber?: number; url: string; filename: string }

/**
 * Prompt for a single slide in an "each slide" run. The user's prompt becomes
 * the style layer; the slide's own headline and emphasis line supply the subject,
 * which is why that scope needs no per-slide prompt writing.
 */
function buildAutoPrompt(slide: any, basePrompt: string): string {
  const topic = [slide.headline, slide.emphasisLine].filter(Boolean).join(' - ')
  const base  = basePrompt?.trim() ? `${basePrompt}. ` : ''
  return `${base}Abstract background image for a carousel slide about: "${topic}". Modern, minimal, clean aesthetic. No text, no people. Geometric shapes, soft gradients, professional.`
}

/** Filesystem-safe fragment of a title or prompt. */
function slugFragment(text: string, words = 4): string {
  return (text || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, words)
    .join('-')
    .slice(0, 48)
}

interface Job {
  id: string
  kind: 'bg-image'
  label: string
  carouselId?: string
  scope: 'single' | 'all' | 'each'
  model?: string
  status: 'running' | 'done' | 'error' | 'cancelled'
  total: number
  done: number
  results: JobResult[]
  errors: string[]
  createdAt: number
  finishedAt?: number
  /** Set by DELETE; checked between spawns and used to kill children. */
  cancelled?: boolean
  procs: Set<{ kill: () => void }>
}

const jobs = new Map<string, Job>()

function pruneJobs() {
  // Keep finished jobs around briefly so a reloading client can still collect
  // results, then drop them. This registry is intentionally in-memory only.
  const cutoff = Date.now() - 30 * 60_000
  for (const [id, j] of jobs) {
    if (j.status !== 'running' && (j.finishedAt ?? 0) < cutoff) jobs.delete(id)
  }
}

function publicJob(j: Job) {
  const { procs, cancelled, ...rest } = j
  return rest
}

app.get('/api/jobs', (c) => {
  pruneJobs()
  const carouselId = c.req.query('carouselId')
  const list = [...jobs.values()]
    .filter((j) => !carouselId || !j.carouselId || j.carouselId === carouselId)
    .sort((a, b) => b.createdAt - a.createdAt)
    .map(publicJob)
  return c.json(list)
})

app.get('/api/jobs/:id', (c) => {
  const j = jobs.get(c.req.param('id'))
  if (!j) return c.json({ error: 'Not found' }, 404)
  return c.json(publicJob(j))
})

app.delete('/api/jobs/:id', (c) => {
  const j = jobs.get(c.req.param('id'))
  if (!j) return c.json({ error: 'Not found' }, 404)
  j.cancelled = true
  for (const p of j.procs) { try { p.kill() } catch { /* already gone */ } }
  if (j.status === 'running') { j.status = 'cancelled'; j.finishedAt = Date.now() }
  return c.json(publicJob(j))
})

// POST /api/jobs/generate-bg
// body: { prompt, scope, slides, carouselId?, model?, useLikeness?, referenceImages? }
// Returns { jobId } straight away.
app.post('/api/jobs/generate-bg', async (c) => {
  const {
    prompt, scope = 'single', slides = [], carouselId, carouselTitle,
    model, useLikeness = false, referenceImages = [],
  } = await c.req.json()

  loadEnv()
  if (!process.env.KIE_API_KEY) {
    return c.json({ error: 'KIE_API_KEY not set. Add it to .env in the project root.' }, 400)
  }
  if (scope !== 'each' && !prompt?.trim()) {
    return c.json({ error: 'prompt is required' }, 400)
  }

  const settings = readSettings()
  const refs: string[] = [...referenceImages]
  const likeness = settings.likenessPath ? expandPath(settings.likenessPath) : ''
  if (useLikeness && likeness && existsSync(likeness)) refs.unshift(likeness)
  const likenessHint = useLikeness && settings.likenessDescription ? ` ${settings.likenessDescription}` : ''
  const finalPrompt = prompt ? `${prompt}${likenessHint}` : prompt

  const targets: any[] = scope === 'each' ? slides : [null]
  const job: Job = {
    id: `job_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
    kind: 'bg-image',
    label: scope === 'each' ? `Backgrounds for ${targets.length} slides` : (prompt || '').slice(0, 48) || 'Background',
    carouselId, scope, model,
    status: 'running',
    total: targets.length,
    done: 0,
    results: [], errors: [],
    createdAt: Date.now(),
    procs: new Set(),
  }
  jobs.set(job.id, job)

  const bgScript = join(import.meta.dir, 'generate_bg_image.py')

  // Images are filed by what they are for, not when they were made: one folder
  // per carousel, and a filename describing the slide and the prompt.
  const folder = slugFragment(carouselTitle || '', 6) || 'unsorted'
  const destDir = join(imagesDir(), folder)
  mkdirSync(destDir, { recursive: true })
  const promptSlug = slugFragment(prompt || '', 4) || 'background'

  const nameFor = (slideNumber?: number) => {
    const base = slideNumber != null
      ? `slide-${String(slideNumber).padStart(2, '0')}-${promptSlug}`
      : scope === 'all' ? `all-slides-${promptSlug}` : `${promptSlug}`
    // Never clobber an earlier take of the same idea
    let name = `${base}.png`
    let n = 2
    while (existsSync(join(destDir, name))) name = `${base}-${n++}.png`
    return name
  }

  // Deliberately not awaited — the response goes back now.
  ;(async () => {
    await Promise.all(targets.map(async (slide: any) => {
      if (job.cancelled) return
      const filename = nameFor(slide?.slideNumber)
      const payload = JSON.stringify({
        prompt: slide ? buildAutoPrompt(slide, finalPrompt) : finalPrompt,
        output: join(destDir, filename),
        referenceImages: refs,
        model,
      })
      const proc = Bun.spawn(['python3', bgScript, payload], { stdout: 'ignore', stderr: 'pipe' })
      job.procs.add(proc as any)
      try {
        const code = await proc.exited
        if (job.cancelled) return
        if (code !== 0) {
          job.errors.push(`${slide ? `Slide ${slide.slideNumber}: ` : ''}${await new Response(proc.stderr).text()}`.slice(0, 400))
        } else {
          job.results.push({
            slideNumber: slide?.slideNumber,
            url: `/local-images/${encodeURIComponent(folder)}/${encodeURIComponent(filename)}`,
            filename,
          })
        }
      } finally {
        job.procs.delete(proc as any)
        job.done += 1
      }
    }))
    if (!job.cancelled) {
      job.status = job.results.length ? 'done' : 'error'
      job.finishedAt = Date.now()
    }
  })()

  return c.json({ jobId: job.id, job: publicJob(job) })
})

// ── PIL Slide Generation ───────────────────────────────────────────────────────

app.post('/api/generate-slide', async (c) => {
  const body = await c.req.json()
  const { slideId, ...slideData } = body

  const filename = `slide_${slideId || Date.now()}.png`
  const outputPath = join(OUTPUT_DIR, filename)
  const payload = JSON.stringify({ ...slideData, handle: creatorHandle(), output: outputPath })
  const scriptPath = join(import.meta.dir, 'generate_slide.py')

  const proc = Bun.spawn(['python3', scriptPath, payload], { stdout: 'ignore', stderr: 'pipe' })
  const [exitCode, stderr] = await Promise.all([
    proc.exited, new Response(proc.stderr).text(),
  ])

  if (exitCode !== 0) return c.json({ error: `PIL generation failed: ${stderr}` }, 500)
  return c.json({ url: `/files/${filename}`, filename })
})

// Export all slides as PNG, PDF, or both → <exportDir>/<slug>/
app.post('/api/export-all', async (c) => {
  const { slides, carouselSlug, format = 'png' } = await c.req.json()
  // format: 'png' | 'pdf' | 'both'
  const slug    = carouselSlug || `carousel_${Date.now()}`
  const slugDir = join(exportDir(), slug)
  mkdirSync(slugDir, { recursive: true })
  const scriptPath = join(import.meta.dir, 'generate_slide.py')

  // Step 1: always generate PNGs — rendered in parallel, one python process per slide
  type Render = { slide: any; filename: string; outputPath: string; payload: string }
  const handle = creatorHandle()   // invariant across the batch
  const renders: Render[] = slides.map((slide: any) => {
    const filename   = `slide_${slide.slideNumber}.png`
    const outputPath = join(slugDir, filename)
    // Media URLs are resolved to absolute paths here, on the server, which owns
    // OUTPUT_DIR — the client has no business knowing where that lives on disk.
    const payload = JSON.stringify({
      ...slide,
      totalSlides:        slides.length,
      handle,
      backgroundImagePath: resolveMediaPath(slide.backgroundImage) ?? undefined,
      backgroundVideoPath: resolveMediaPath(slide.backgroundVideo) ?? undefined,
      insetImagePath:      resolveMediaPath(slide.insetImageUrl) ?? undefined,
      output: outputPath,
    })
    return { slide, filename, outputPath, payload }
  })

  const outcomes = await Promise.all(renders.map(async ({ slide, payload }) => {
    const proc     = Bun.spawn(['python3', scriptPath, payload], { stdout: 'ignore', stderr: 'pipe' })
    const exitCode = await proc.exited
    if (exitCode !== 0) {
      return { ok: false as const, slideNumber: slide.slideNumber, stderr: await new Response(proc.stderr).text() }
    }
    return { ok: true as const }
  }))

  const failed = outcomes.find((o) => !o.ok)
  if (failed && !failed.ok) {
    return c.json({ error: `Slide ${failed.slideNumber} failed: ${failed.stderr}` }, 500)
  }

  // Keep slide order stable for the PDF regardless of which render finished first
  const pngPaths   = renders.map((r) => r.outputPath)
  const pngResults = renders.map((r) => ({
    slideNumber: r.slide.slideNumber,
    url:         `/carousel-output/${slug}/${r.filename}`,
    filename:    r.filename,
  }))

  // Step 2: generate PDF if requested
  let pdfResult: { url: string; filename: string } | null = null
  if (format === 'pdf' || format === 'both') {
    const pdfFilename = `${slug}.pdf`
    const pdfPath     = join(slugDir, pdfFilename)
    const pdfPayload  = JSON.stringify(pngPaths)

    const proc = Bun.spawn(['python3', scriptPath, '--pdf', pdfPayload, pdfPath], { stdout: 'ignore', stderr: 'pipe' })
    const exitCode = await proc.exited
    if (exitCode !== 0) {
      const stderr = await new Response(proc.stderr).text()
      return c.json({ error: `PDF generation failed: ${stderr}` }, 500)
    }
    pdfResult = { url: `/carousel-output/${slug}/${pdfFilename}`, filename: pdfFilename }
  }

  return c.json({
    slides: format === 'pdf' ? [] : pngResults,
    pdf: pdfResult,
    slug,
    outputDir: slugDir,
  })
})

// One card that carries the whole carousel: the headline from every slide,
// stacked in a terminal block. A recap someone can screenshot, and the still
// a short video is built from. Reuses the terminal variant rather than being
// a new layout, so it looks like the set it came from.
app.post('/api/summary-slide', async (c) => {
  const {
    carouselId, headline, emphasisLine, points: override, save = false,
    video: makeVideo = false, videoSeconds = 5, audio,
    // A card read for five seconds on a phone needs bigger type than one you
    // can stop and pinch-zoom, so video defaults larger than the still.
    textScale, videoMargin = 55 / 1080,
  } = await c.req.json()
  const path = join(CAROUSELS_DIR, `${carouselId}.json`)
  if (!existsSync(path)) return c.json({ error: 'Carousel not found' }, 404)
  const carousel = JSON.parse(readFileSync(path, 'utf8'))
  const slides: any[] = carousel.slides ?? []
  if (!slides.length) return c.json({ error: 'Carousel has no slides' }, 400)

  const cover = slides[0] ?? {}
  // Skip the cover and any CTA: they are framing, not points. Prefer the
  // emphasis line, which is the takeaway — headlines here are labels like
  // "the test" that mean nothing lifted out of their slide. Caller can
  // override entirely.
  const points: string[] = Array.isArray(override) && override.length
    ? override.map((p: unknown) => String(p).trim()).filter(Boolean)
    : slides
        .filter((sl) => sl.type !== 'cover' && sl.type !== 'cta')
        .map((sl) => (sl.emphasisLine || sl.headline || '').trim())
        .filter(Boolean)

  const summary = {
    slideNumber: 1,
    type: 'cover',
    variant: 'terminal',
    headline: headline || 'all of it',
    emphasisLine: emphasisLine || (cover.emphasisLine ?? ''),
    bgColor: cover.bgColor || '#12141A',
    textColor: cover.textColor || '#EEECE8',
    accentColor: cover.accentColor || '#E07355',
    terminalTitle: 'summary',
    terminalLines: points.map((p, i) => `${i + 1}. ${p}`),
    textScale: textScale ?? (makeVideo ? 1.3 : 1.0),
  }

  const slug = slugFromTitle(carousel.title)
  const slugDir = join(exportDir(), slug)
  mkdirSync(slugDir, { recursive: true })
  const outputPath = join(slugDir, 'summary.png')
  const payload = JSON.stringify({
    ...summary, totalSlides: 1, handle: creatorHandle(), output: outputPath,
  })
  const proc = Bun.spawn(['python3', join(import.meta.dir, 'generate_slide.py'), payload],
                         { stdout: 'ignore', stderr: 'pipe' })
  const [code, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()])
  if (code !== 0) return c.json({ error: `summary render failed: ${stderr}` }, 500)

  if (save) {
    carousel.slides = [...slides, { ...summary, slideNumber: slides.length + 1, type: 'content' }]
    writeFileSync(path, JSON.stringify(carousel, null, 2))
  }

  // Optionally carry it through to a vertical clip: reframe for TikTok, then
  // hold it for a few seconds with an audio bed if one is configured.
  let video: string | undefined
  let hasAudio = false
  if (makeVideo) {
    const framed = join(slugDir, 'summary-tiktok.png')
    // Tighter margin than a swipeable carousel: a single card has no
    // neighbouring slides to clear, so it can use more of the frame.
    const p1 = Bun.spawn(['python3', join(import.meta.dir, 'tiktok_safe.py'), JSON.stringify({
      input: outputPath, output: framed, bgColor: summary.bgColor,
      margin: Math.round(videoMargin * 1080),
    })], { stdout: 'ignore', stderr: 'pipe' })
    const [c1, e1] = await Promise.all([p1.exited, new Response(p1.stderr).text()])
    if (c1 !== 0) return c.json({ error: `summary reframe failed: ${e1}` }, 500)

    const bed = resolveAudio(audio)
    hasAudio = !!bed
    const videoPath = join(slugDir, `${slug}-summary.mp4`)
    const p2 = Bun.spawn(['python3', join(import.meta.dir, 'slides_to_video.py'), JSON.stringify({
      inputs: [framed], output: videoPath, perSlide: videoSeconds, coverBoost: 1,
      ...(bed ? { audio: bed } : {}),
    })], { stdout: 'ignore', stderr: 'pipe' })
    const [c2, e2] = await Promise.all([p2.exited, new Response(p2.stderr).text()])
    if (c2 !== 0) return c.json({ error: `summary video failed: ${e2}` }, 500)
    video = `/carousel-output/${encodeURIComponent(slug)}/${slug}-summary.mp4`
  }

  return c.json({
    ok: true, slug, points,
    url: `/carousel-output/${encodeURIComponent(slug)}/summary.png`,
    slide: summary, savedToCarousel: save,
    video, hasAudio,
    // Say it plainly rather than shipping a silent clip that looks finished
    audioNote: makeVideo && !hasAudio
      ? 'No audio bed configured. Drop a track in audio/ and set audioPath, or let TikTok add one at post time.'
      : undefined,
  })
})

// ── Platform variants ─────────────────────────────────────────────────────────

// Re-frame an exported carousel for TikTok: every slide is placed inside a
// 1080x1920 canvas clear of TikTok's caption block, action rail and tab chrome.
// Writes to <slug>/tiktok/ so the gallery picks it up as a variant.
// Available here and from the CLI (tiktok_safe.py) so both routes agree.
app.post('/api/export-tiktok', async (c) => {
  // JPG by default: TikTok photo slideshows take JPG, not PNG.
  const { carouselSlug, bgColor = '#12141A', margin, topBias, format = 'jpg' } = await c.req.json()
  if (!carouselSlug) return c.json({ error: 'carouselSlug is required' }, 400)

  const slugDir = join(exportDir(), carouselSlug)
  if (!existsSync(slugDir)) return c.json({ error: `No export at ${carouselSlug}` }, 404)

  const outDir = join(slugDir, 'tiktok')
  mkdirSync(outDir, { recursive: true })
  const script = join(import.meta.dir, 'tiktok_safe.py')

  // Only stills reframe. Where a slide is a video, its PNG counterpart is used,
  // so the TikTok set is complete but that slide does not move.
  const stills = readdirSync(slugDir).filter((f) => /^slide_\d+\.png$/i.test(f))
  const videos = readdirSync(slugDir).filter((f) => /^slide_\d+\.mp4$/i.test(f))
  const stillNumbers = new Set(stills.map((f) => f.match(/\d+/)![0]))
  if (!stills.length) return c.json({ error: 'No slide PNGs to reframe' }, 400)

  const outcomes = await Promise.all(stills.map(async (name) => {
    const payload = JSON.stringify({
      input: join(slugDir, name), output: join(outDir, name), bgColor, format,
      ...(margin != null ? { margin } : {}), ...(topBias != null ? { topBias } : {}),
    })
    const proc = Bun.spawn(['python3', script, payload], { stdout: 'ignore', stderr: 'pipe' })
    const [code, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()])
    return code === 0 ? { ok: true as const, name } : { ok: false as const, name, stderr }
  }))

  const failed = outcomes.filter((o) => !o.ok)
  if (failed.length) return c.json({ error: `Failed: ${failed.map((f: any) => f.name).join(', ')}` }, 500)

  return c.json({
    ok: true,
    count: stills.length,
    outputDir: outDir,
    // A video slide reframed from its still: the set is complete, but that
    // slide is static on TikTok. Saying so beats implying the motion carried.
    staticFromVideo: videos.filter((v) => stillNumbers.has(v.match(/\d+/)![0])),
    // A video slide with no still at all really is missing from the set.
    missing: videos.filter((v) => !stillNumbers.has(v.match(/\d+/)![0])),
  })
})

// Play a whole carousel as one short vertical video. A photo carousel and a
// video are different formats on TikTok with different reach, and this is the
// video one: the slides you already have, held a beat each, at 1080x1920.
// Prefers the tiktok/ reframed set so nothing sits under TikTok's UI.
app.post('/api/carousel-video', async (c) => {
  const { carouselSlug, perSlide = 2.5, fade = 0.2, audio, coverBoost } = await c.req.json()
  if (!carouselSlug) return c.json({ error: 'carouselSlug is required' }, 400)

  const slugDir = join(exportDir(), carouselSlug)
  if (!existsSync(slugDir)) return c.json({ error: `No export at ${carouselSlug}` }, 404)

  // The reframed set already clears TikTok's overlays; fall back to the 4:5
  // slides, which slides_to_video will letterbox rather than crop.
  const tiktokDir = join(slugDir, 'tiktok')
  const sourceDir = existsSync(tiktokDir) ? tiktokDir : slugDir
  const inputs = readdirSync(sourceDir)
    .filter((f) => /^slide_\d+\.png$/i.test(f))
    .sort((a, b) => parseInt(a.match(/\d+/)![0]) - parseInt(b.match(/\d+/)![0]))
    .map((f) => join(sourceDir, f))
  if (!inputs.length) return c.json({ error: 'No slide PNGs found' }, 400)

  const filename = `${carouselSlug}-tiktok.mp4`
  const outputPath = join(slugDir, filename)
  const payload = JSON.stringify({
    inputs, output: outputPath, perSlide, fade,
    ...(coverBoost != null ? { coverBoost } : {}),
    ...(resolveAudio(audio) ? { audio: resolveAudio(audio) } : {}),
  })
  const proc = Bun.spawn(['python3', join(import.meta.dir, 'slides_to_video.py'), payload],
                         { stdout: 'ignore', stderr: 'pipe' })
  const [code, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()])
  if (code !== 0) return c.json({ error: `carousel video failed: ${stderr}` }, 500)

  // Cover is held coverBoost times longer, so the total is not a flat multiple
  const boost = coverBoost ?? 1.4
  const duration = Math.round(perSlide * (boost + inputs.length - 1) * 10) / 10
  return c.json({
    ok: true,
    url: `/carousel-output/${encodeURIComponent(carouselSlug)}/${filename}`,
    filename, slideCount: inputs.length, perSlide, duration,
    usedReframed: sourceDir === tiktokDir,
    // Under a second and a half, body copy cannot be read at a glance.
    tooFast: perSlide < 1.5,
  })
})

// ── Slide video (a moving carousel slide) ─────────────────────────────────────

// Instagram carousels take video slides next to image slides, so slide 1 can
// move while the rest stay still. Renders the slide furniture on alpha, then
// composites it over a still (slow push-in) or a supplied clip. Writes the mp4
// next to the exported PNGs so the whole post lives in one folder.
// Not flash-video: that one is 1080x1920 for standalone Reels.
app.post('/api/slide-video', async (c) => {
  const { slide, carouselSlug, duration = 5, zoom = 1.08, audio } = await c.req.json()
  if (!slide) return c.json({ error: 'slide is required' }, 400)

  const slug    = carouselSlug || `carousel_${Date.now()}`
  const slugDir = join(exportDir(), slug)
  mkdirSync(slugDir, { recursive: true })

  const overlayPath = join(OUTPUT_DIR, `overlay_${Date.now()}.png`)
  const overlayPayload = JSON.stringify({
    ...slide, handle: creatorHandle(), transparent: true, output: overlayPath,
  })
  const slideScript = join(import.meta.dir, 'generate_slide.py')
  const overlayProc = Bun.spawn(['python3', slideScript, overlayPayload], { stdout: 'ignore', stderr: 'pipe' })
  if (await overlayProc.exited !== 0) {
    return c.json({ error: `overlay render failed: ${await new Response(overlayProc.stderr).text()}` }, 500)
  }

  const filename = `slide_${slide.slideNumber ?? 1}.mp4`
  const outputPath = join(slugDir, filename)
  const payload = JSON.stringify({
    overlay: overlayPath,
    source:  resolveMediaPath(slide.backgroundVideo) ?? resolveMediaPath(slide.backgroundImage) ?? undefined,
    audio:   resolveAudio(audio),
    duration, zoom, output: outputPath,
  })
  const videoProc = Bun.spawn(['python3', join(import.meta.dir, 'slide_video.py'), payload],
                       { stdout: 'ignore', stderr: 'pipe' })
  const code = await videoProc.exited
  try { unlinkSync(overlayPath) } catch { /* best effort */ }
  if (code !== 0) {
    return c.json({ error: `slide video failed: ${await new Response(videoProc.stderr).text()}` }, 500)
  }
  return c.json({ url: `/carousel-output/${slug}/${filename}`, filename, outputDir: slugDir })
})

// ── Flash video generation ────────────────────────────────────────────────────

app.post('/api/flash-video', async (c) => {
  const body = await c.req.json()
  const { carouselId, slideNumber, carouselTitle } = body
  const ts = Date.now()
  const filename = `flash_${carouselId || 'carousel'}_s${slideNumber || 1}_${ts}.mp4`
  const outputPath = join(OUTPUT_DIR, filename)
  const payload = JSON.stringify({ ...body, output: outputPath, outputDir: OUTPUT_DIR })
  const scriptPath = join(import.meta.dir, 'flash_video.py')
  const proc = Bun.spawn(['python3', scriptPath, payload], { stdout: 'ignore', stderr: 'pipe' })
  const [exitCode, stderr] = await Promise.all([
    proc.exited, new Response(proc.stderr).text(),
  ])
  if (exitCode !== 0) return c.json({ error: `Flash video failed: ${stderr}` }, 500)

  // Save JSON sidecar
  const meta = {
    id: filename.replace('.mp4', ''),
    carouselId: carouselId || null,
    carouselTitle: carouselTitle || null,
    slideNumber: slideNumber || 1,
    style: body.style || 'statement',
    duration: body.duration || 5,
    headline: body.headline || '',
    emphasisLine: body.emphasisLine || '',
    subText: body.subText || '',
    ctaText: body.ctaText || '',
    listItems: body.listItems || [],
    summaryLine: body.summaryLine || '',
    handle: body.handle || creatorHandle(),
    bgColor: body.bgColor || '#F5F0EB',
    textColor: body.textColor || '#1B1B1B',
    accentColor: body.accentColor || '#E07355',
    backgroundVideo: body.backgroundVideo || null,
    backgroundImage: body.backgroundImage || null,
    overlayOpacity: body.overlayOpacity ?? 0.45,
    mp4: filename,
    url: `/files/${filename}`,
    generatedAt: new Date().toISOString(),
  }
  writeFileSync(join(OUTPUT_DIR, filename.replace('.mp4', '.json')), JSON.stringify(meta, null, 2))

  // Update flash_index.json (newest first, deduplicated by carouselId+slideNumber)
  const indexPath = join(OUTPUT_DIR, 'flash_index.json')
  let index: any[] = []
  try { index = JSON.parse(readFileSync(indexPath, 'utf8')) } catch { /* new */ }
  index = index.filter((e: any) => !(e.carouselId === meta.carouselId && e.slideNumber === meta.slideNumber))
  index.unshift(meta)
  writeFileSync(indexPath, JSON.stringify(index, null, 2))

  return c.json({ url: `/files/${filename}`, filename, meta })
})

app.get('/api/flash-videos', (c) => {
  const indexPath = join(OUTPUT_DIR, 'flash_index.json')
  try { return c.json(JSON.parse(readFileSync(indexPath, 'utf8'))) } catch { return c.json([]) }
})

// ── Exported carousel library ─────────────────────────────────────────────────

// GET /api/exports
// Everything previously exported to disk, newest first. This is distinct from
// /api/carousels: those are editable projects, these are finished output.
// A carousel folder holds the default set at its root, and one subfolder per
// platform variant (tiktok/, linkedin/, …). Variants were invisible before:
// you could not tell from the UI that a TikTok set existed, let alone view it.
function readSlideSet(dir: string, urlPrefix: string) {
  let files: string[] = []
  try { files = readdirSync(dir) } catch { return null }

  // slide_1.png, slide_2.mp4 … sorted numerically, not lexically. A slide can
  // be a video, and an mp4 wins over a png of the same number since it is the
  // newer artifact for that slide.
  const byNumber = new Map<number, string>()
  for (const f of files) {
    const m = f.match(/^slide_(\d+)\.(png|jpe?g|mp4)$/i)
    if (!m) continue
    const n = parseInt(m[1])
    if (!byNumber.has(n) || m[2].toLowerCase() === 'mp4') byNumber.set(n, f)
  }
  const slides = [...byNumber.entries()].sort((a, b) => a[0] - b[0]).map(([, f]) => f)
  if (!slides.length) return null

  let modified = 0
  try { modified = statSync(join(dir, slides[0])).mtimeMs } catch { /* ignore */ }

  return {
    slideCount: slides.length,
    slides: slides.map((f) => `${urlPrefix}/${f}`),
    cover: `${urlPrefix}/${slides[0]}`,
    files,
    modified,
  }
}

app.get('/api/exports', (c) => {
  const dir = exportDir()
  if (!existsSync(dir)) return c.json({ exportDir: dir, carousels: [] })

  const entries = readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => {
      const slugDir = join(dir, e.name)
      const base = `/carousel-output/${encodeURIComponent(e.name)}`
      const root = readSlideSet(slugDir, base)
      if (!root) return null

      // Any subfolder holding slide_N files is a platform variant, named after
      // the folder. Nothing is hardcoded, so a new one just shows up.
      const variants: Record<string, any> = {}
      let subdirs: string[] = []
      try {
        subdirs = readdirSync(slugDir, { withFileTypes: true })
          .filter((d) => d.isDirectory()).map((d) => d.name)
      } catch { /* ignore */ }
      for (const name of subdirs) {
        const set = readSlideSet(join(slugDir, name), `${base}/${encodeURIComponent(name)}`)
        if (set) variants[name] = { slideCount: set.slideCount, slides: set.slides, cover: set.cover, modified: set.modified }
      }

      const pdf = root.files.find((f) => f.toLowerCase().endsWith('.pdf'))
      // Carousel-level videos: any mp4 at the root that is not a slide, e.g.
      // the whole set played as one vertical clip. Without this the file is
      // written to disk and then invisible to the app that wrote it.
      const videos = root.files
        .filter((f) => /\.(mp4|mov|webm)$/i.test(f) && !/^slide_\d+\./i.test(f))
        .sort()
        .map((f) => ({ filename: f, url: `${base}/${f}` }))
      // A variant older than the default set means someone re-exported and the
      // variant was left behind. Surfacing it beats silently posting stale art.
      const stale = Object.keys(variants).filter((k) => variants[k].modified < root.modified - 1000)

      return {
        slug: e.name,
        slideCount: root.slideCount,
        slides: root.slides,
        cover: root.cover,
        pdf: pdf ? `${base}/${pdf}` : null,
        hasCaptions: root.files.includes('captions.md'),
        videos,
        modified: root.modified,
        variants,                       // { tiktok: {...}, … }
        platforms: ['default', ...Object.keys(variants)],
        staleVariants: stale,
      }
    })
    .filter(Boolean) as any[]

  entries.sort((a, b) => b.modified - a.modified)
  return c.json({ exportDir: dir, carousels: entries })
})

// Captions written alongside an export, so they can be read without leaving the app
app.get('/api/exports/:slug/captions', (c) => {
  const path = resolveMediaPath(`/carousel-output/${c.req.param('slug')}/captions.md`)
  if (!path) return c.json({ error: 'No captions for this carousel' }, 404)
  return c.json({ markdown: readFileSync(path, 'utf8') })
})

// ── Generated image library ───────────────────────────────────────────────────

// Images available to apply to a slide, from two sources:
//   generated — bg_*.png this app produced, in output/
//   local     — anything under the images directory, including batches made by
//               the Claude Code kie-* skills. Scanned one level deep so
//               per-session subfolders show up as groups.
app.get('/api/images', (c) => {
  const IMG = /\.(png|jpe?g|webp)$/i
  const items: any[] = []

  try {
    for (const f of readdirSync(OUTPUT_DIR)) {
      if (!f.startsWith('bg_') || !IMG.test(f)) continue
      let mtime = 0
      try { mtime = statSync(join(OUTPUT_DIR, f)).mtimeMs } catch { /* skip */ }
      items.push({ source: 'generated', group: 'Generated here', filename: f, url: `/files/${f}`, mtime })
    }
  } catch { /* no output dir yet */ }

  const root = imagesDir()
  const walk = (dir: string, group: string, depth: number) => {
    let entries: any[] = []
    try { entries = readdirSync(dir, { withFileTypes: true }) } catch { return }
    for (const e of entries) {
      const full = join(dir, e.name)
      if (e.isDirectory()) {
        if (depth < 2) walk(full, e.name, depth + 1)
        continue
      }
      if (!IMG.test(e.name)) continue
      const rel = full.slice(root.length + 1).split(sep).map(encodeURIComponent).join('/')
      let mtime = 0
      try { mtime = statSync(full).mtimeMs } catch { /* skip */ }
      items.push({ source: 'local', group, filename: e.name, url: `/local-images/${rel}`, mtime })
    }
  }
  walk(root, 'Local images', 0)

  items.sort((a, b) => b.mtime - a.mtime)
  return c.json({ imagesDir: root, images: items })
})

// Serve a file from the local image library
app.get('/local-images/*', async (c) => {
  const rel = new URL(c.req.url).pathname.slice('/local-images/'.length)
  const filePath = resolveMediaPath(`/local-images/${rel}`)
  if (!filePath) return c.text('Not found', 404)
  return new Response(Bun.file(filePath), {
    headers: { 'Content-Type': mediaType(filePath), 'Cache-Control': 'no-store',
               'Accept-Ranges': 'bytes' },
  })
})

app.delete('/api/images/:filename', (c) => {
  const filename = c.req.param('filename')
  if (!filename.startsWith('bg_') || !filename.endsWith('.png')) return c.json({ error: 'Invalid filename' }, 400)
  const filePath = join(OUTPUT_DIR, filename)
  if (existsSync(filePath)) unlinkSync(filePath)
  return c.json({ ok: true })
})

// ── Static file serving ───────────────────────────────────────────────────────

// Serve exported carousel output from <exportDir>/<slug>/
// Wildcard, not :slug/:filename — a platform variant lives one level deeper
// (<slug>/tiktok/slide_1.png) and a two-segment route silently fell through to
// the SPA, answering an <img> with index.html. resolveMediaPath still blocks
// anything escaping the export directory.
app.get('/carousel-output/*', async (c) => {
  const rel = new URL(c.req.url).pathname.slice('/carousel-output/'.length)
  const filePath = resolveMediaPath(`/carousel-output/${rel}`)
  if (!filePath) return c.text('Not found', 404)
  const filename = rel.split('/').pop() || rel
  const file = Bun.file(filePath)
  const contentType = mediaType(filename)
  const disposition = contentType === 'application/pdf'
    ? `attachment; filename="${filename}"` : 'inline'
  return new Response(file, {
    // Accept-Ranges lets the player seek instead of refusing to scrub
    headers: { 'Content-Type': contentType, 'Cache-Control': 'no-store',
               'Content-Disposition': disposition, 'Accept-Ranges': 'bytes' },
  })
})

app.get('/files/:filename', async (c) => {
  const filename = c.req.param('filename')
  const filePath = resolveMediaPath(`/files/${filename}`)
  if (!filePath) return c.text('Not found', 404)
  const file = Bun.file(filePath)
  const contentType = mediaType(filename)
  const disposition = contentType === 'application/pdf'
    ? `attachment; filename="${filename}"` : 'inline'
  return new Response(file, {
    headers: { 'Content-Type': contentType, 'Cache-Control': 'no-store', 'Content-Disposition': disposition, 'Accept-Ranges': 'bytes' },
  })
})

// Serve the built client. Static assets must be matched before the SPA
// fallback, otherwise every /assets/*.js request is answered with index.html
// and the built app loads a blank page.
const DIST_DIR = join(import.meta.dir, 'client', 'dist')

// Browsers refuse to execute a type="module" script served without a JavaScript
// MIME type, so serving assets with no Content-Type breaks the built app.
const MIME: Record<string, string> = {
  '.js':   'text/javascript',
  '.mjs':  'text/javascript',
  '.css':  'text/css',
  '.html': 'text/html',
  '.json': 'application/json',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.ico':  'image/x-icon',
  '.woff': 'font/woff',
  '.woff2':'font/woff2',
  '.ttf':  'font/ttf',
  '.map':  'application/json',
}

app.get('*', async (c) => {
  const indexPath = join(DIST_DIR, 'index.html')
  if (!existsSync(indexPath)) return c.text('Run `bun run client` for the dev server', 200)

  const urlPath = new URL(c.req.url).pathname
  const asset   = resolve(DIST_DIR, '.' + urlPath)
  if ((asset === DIST_DIR || asset.startsWith(DIST_DIR + sep)) && existsSync(asset) && statSync(asset).isFile()) {
    const ext  = asset.slice(asset.lastIndexOf('.')).toLowerCase()
    const type = MIME[ext]
    return new Response(Bun.file(asset), type ? { headers: { 'Content-Type': type } } : undefined)
  }
  // Unknown path → hand back index.html so client-side routing works
  return new Response(Bun.file(indexPath), { headers: { 'Content-Type': 'text/html' } })
})

console.log('🎨 Carousel Studio server running on http://localhost:3010')
export default { port: 3010, fetch: app.fetch }
