import { existsSync, mkdirSync } from 'fs'
import { homedir } from 'os'
import { join, resolve, sep } from 'path'
import { readSettings } from './settings'

/**
 * Where everything lives.
 *
 * APP_ROOT is resolved once, from this file's own location, and every other
 * path hangs off it. That matters more than it looks: the code these were
 * extracted from used `import.meta.dir` in twenty-four places, which meant "the
 * directory of the file I am written in" — correct while everything was one
 * file at the repo root, and silently wrong the moment any of it moved down a
 * directory. Nothing here may use import.meta.dir except the line below.
 */
export const APP_ROOT = join(import.meta.dir, '..')

export const OUTPUT_DIR     = join(APP_ROOT, 'output')
export const FRAMEWORKS_DIR = join(APP_ROOT, 'frameworks')
export const CAROUSELS_DIR  = join(APP_ROOT, 'carousels')
export const THEMES_DIR     = join(APP_ROOT, 'themes')
export const DIST_DIR       = join(APP_ROOT, 'client', 'dist')
export const SETTINGS_FILE  = join(APP_ROOT, 'settings.json')

/** `~` in a configured path means the user's home directory. */
export function expandPath(p: string): string {
  return p.startsWith('~')
    ? join(homedir(), p.slice(1).replace(/^[/\\]/, ''))
    : resolve(p)
}

/** Where finished carousels land. Defaults to a folder inside the app so a
 *  fresh clone works with no configuration; point it somewhere else (e.g. a
 *  content repo) with CAROUSEL_EXPORT_DIR or `exportDir` in settings.json. */
export function exportDir(): string {
  const configured = process.env.CAROUSEL_EXPORT_DIR || readSettings().exportDir
  return configured ? expandPath(configured) : join(APP_ROOT, 'exports')
}

/** Local image library. Anything dropped here — including batches generated by
 *  the Claude Code kie-* skills — shows up in the app's Image Library.
 *  Override with CAROUSEL_IMAGES_DIR or `imagesDir` in settings.json. */
export function imagesDir(): string {
  const configured = process.env.CAROUSEL_IMAGES_DIR || readSettings().imagesDir
  return configured ? expandPath(configured) : join(APP_ROOT, 'images')
}

/** Audio beds for generated video. Empty by default; see audio/README.md. */
export function audioDir(): string {
  const configured = process.env.CAROUSEL_AUDIO_DIR || readSettings().audioDir
  return configured ? expandPath(configured) : join(APP_ROOT, 'audio')
}

/**
 * Resolve a client-side media URL to an absolute path on disk.
 *
 * Accepts the four URL prefixes the app serves from and returns null for
 * anything else — including any path that escapes its base directory, which is
 * the only reason this is a function rather than a join.
 */
export function resolveMediaPath(url: string | undefined): string | null {
  if (!url) return null
  const bases: [string, () => string][] = [
    ['/files/', () => OUTPUT_DIR],
    ['/carousel-output/', exportDir],
    ['/local-images/', imagesDir],
    ['/local-audio/', audioDir],
  ]
  const match = bases.find(([prefix]) => url.startsWith(prefix))
  if (!match) return null

  const base = match[1]()
  const resolved = resolve(base, decodeURIComponent(url.slice(match[0].length)))
  if (resolved !== base && !resolved.startsWith(base + sep)) return null
  return existsSync(resolved) ? resolved : null
}

export function ensureDirs() {
  mkdirSync(OUTPUT_DIR, { recursive: true })
  mkdirSync(CAROUSELS_DIR, { recursive: true })
  try { mkdirSync(imagesDir(), { recursive: true }) } catch { /* non-fatal */ }
}

/** The audio bed to lay under a video: what the caller asked for, else the
 *  configured default, else nothing. Never guesses at a file on disk. */
export function resolveAudio(requested?: string): string | undefined {
  const explicit = requested ? resolveMediaPath(requested) : null
  if (explicit) return explicit
  const configured = readSettings().audioPath
  if (!configured) return undefined
  const abs = expandPath(configured.startsWith('/') || configured.startsWith('~')
    ? configured : join(APP_ROOT, configured))
  return existsSync(abs) ? abs : undefined
}
